export { html } from "./html.js";
export { css } from "./css.js";
export class Symbiote<S> extends HTMLElement {
    static lazyObserver: IntersectionObserver;
    static __tpl: HTMLTemplateElement;
    static mcpToolMode: boolean;
    static componentDescription: string | (() => string | Promise<string>);
    static set devMode(val: boolean);
    static get devMode(): boolean;
    static template: string;
    static parseProp<T extends Symbiote<any>>(prop: string, fnCtx: T): import("./parseProp.js").ParsedProp | null;
    static animateOut: typeof animateOut;
    static reg(tagName?: string, isAlias?: boolean): typeof Symbiote;
    static get is(): string;
    static bindAttributes(desc: {
        [x: string]: string;
    }): void;
    static addRootStyles(styles: string | CSSStyleSheet): void;
    static addShadowStyles(styles: string | CSSStyleSheet): void;
    static set rootStyles(styles: string | CSSStyleSheet);
    static set shadowStyles(styles: string | CSSStyleSheet);
    constructor();
    componentDescription: string | (() => string | Promise<string>);
    get Symbiote(): typeof Symbiote;
    initCallback(): void;
    renderCallback(): void;
    render(template?: string | DocumentFragment, shadow?: boolean): void;
    ssrMode: any;
    init$: S;
    cssInit$: {
        [x: string]: any;
    };
    templateProcessors: Set<(fr: DocumentFragment | Symbiote<any>, fnCtx: Symbiote<any>) => void>;
    ref: {
        [x: string]: any;
    };
    allSubs: Set<any>;
    pauseRender: boolean;
    renderShadow: boolean;
    readyToDestroy: boolean;
    processInnerHtml: boolean;
    isoMode: boolean;
    allowCustomTemplate: boolean;
    isVirtual: boolean;
    allowTemplateInits: boolean;
    lazyMode: boolean;
    mcpToolMode: boolean;
    syncWebMCPTools(): void;
    unregisterWebMCPTools(): void;
    get cssCtxName(): string;
    get ctxName(): string;
    get localCtx(): PubSub<any>;
    get sharedCtx(): PubSub<any>;
    sub<T extends keyof S>(prop: T, handler: (value: S[T]) => void, init?: boolean): void;
    notify(prop: string): void;
    has(prop: string): any;
    add<T extends keyof S>(prop: string, val: S[T], rewrite?: boolean): void;
    add$(obj: Partial<S>, rewrite?: boolean): void;
    get $(): S;
    set$(kvObj: Partial<S>, forcePrimitives?: boolean): void;
    initAttributeObserver(): void;
    attributeMutationObserver: MutationObserver;
    initChildren: ChildNode[];
    connectedOnce: boolean;
    connectedCallback(): void;
    destroyCallback(): void;
    destructionDelay: number;
    disconnectedCallback(): void;
    attributeChangedCallback(name: any, oldVal: any, newVal: any): void;
    getCssData(propName: string, silentCheck?: boolean): any;
    updateCssData: () => void;
    bindCssData(propName: string, initValue?: any): void;
    dropCssDataCache(): void;
    defineAccessor(propName: string, handler?: Function, isAsync?: boolean): void;
    #private;
}
export default Symbiote;
import PubSub from './PubSub.js';
import { DICT } from './dictionary.js';
import { animateOut } from './animateOut.js';
export { PubSub, DICT };
//# sourceMappingURL=Symbiote.d.ts.map